language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

matrix:
  allow_failures:
    - env: DB=pgsql
    - php: hhvm
      env: DB=sqlite
  exclude:
    - php: hhvm
      env: DB=pgsql # driver currently unsupported by HHVM

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS acl_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE acl_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS acl_tests;'; fi"
  - composer require satooshi/php-coveralls:dev-master --dev --no-interaction --prefer-source
  - mkdir -p build/logs

script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then vendor/bin/phpunit --configuration tests/travis/$DB.phpunit.xml --colors --coverage-clover ./build/logs/clover.xml; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then vendor/bin/phpunit --configuration tests/travis/$DB.phpunit.xml --colors; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then vendor/bin/coveralls -v; fi
